[package]
name = "libapuadj"
version = "0.1.0"
edition = "2021"

[dependencies]

[build-dependencies]
bindgen = "0.71.0"
cmake = "0.1.45"
winres = "0.1"

[[bin]]

name="set_apu_limit"
path="bin/set_apu_limit.rs"

